/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndkjnidemo_NdkJniUtils */

#ifndef _Included_com_ndkjnidemo_NdkJniUtils
#define _Included_com_ndkjnidemo_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndkjnidemo_NdkJniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndkjnidemo_NdkJniUtils_getStringFormC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
